actors:
  riku:
    image_url: /images/actors/riku.jpg
    name: Riku
    url: https://rikuchan.jp
author: riku
description: Rikuchan.fmは竹中陸が日常を語るポッドキャスト番組です。
description_long: Rikuchan.fmは竹中陸が日常を語るポッドキャスト番組です。プログラミング、音楽（ピアノ）、将棋、好きなTVCM、コーヒー、いいロケーションなど
email: riijon@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: rikuchanfm
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/rikuchan-fm/id1551545808
spotify_podcast_url: https://open.spotify.com/show/7M5Tsl9huKXljMOjTgATce
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Rikuchan.fm
url: https://rikuchan-jp.github.io
